
server:
  port: ${PORT:9023}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
  instance:
    hostname: localhost
    nonSecurePort: 80

---
spring:
  profiles: cloud
  

