export const CREATE_TRADE = "TRADE.CREATE";
export const EDIT_TRADE = "TRADE.EDIT";
export const DELETE_TRADE  = "TRADE.DELETE";

export const SERACH_TRADES = "TRADE.SEARCH";

export const UPDATE_TICKER = "TICKER.UPDATE";

export const REF_DATA_INIT_LOADING = "REFDATA.INIT_LOADING";
export const REF_DATA_INIT = "REFDATA.INIT_DATA";

export const TRADE_DATA_INIT_LOADING = "TRADE.INIT_LOADING";
export const TRADE_DATA_INIT = "TRADE.INIT_DATA";


